### ISSUE TITLE
A problem during fresh install

### ISSUE THREAD

**Issue by a-berg** [shaunsingh/nyoom.nvim#35]
Hello, I recently forked your config and followed the steps regarding nix (so I went into the `nix develop`).
I'm facing the following issue: when I first call nvim in the spawned nix shell, it gives an error regarding the installation of `hotpot`

```
E5113: Error while calling lua chunk: /home/adrian/code/github.com/a-berg/aum.nvim/init.lua:42: module 'hotpot' not found:
        no field package.preload['hotpot']
        no file './share/lua/5.1/hotpot.lua'
        no file './hotpot.lua'
        no file './hotpot/init.lua'
        no file './lib/lua/5.1/hotpot.so'
        no file './hotpot.so'
        no file './lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        ~/code/github.com/a-berg/aum.nvim/init.lua:42: in main chunk
```

The second time I launch `nvim`, it instead complains of not finding `init`. 
```
E5113: Error while calling lua chunk: ./init.lua:43: loop or previous error loading module 'init'
stack traceback:
        [C]: in function 'require'
        ./init.lua:43: in main chunk
        [C]: in function 'require'
        ~/code/github.com/a-berg/aum.nvim/init.lua:43: in main chunk
```
I interpret this as nvim finding the hotpot package (it is indeed installed in `~/.local/share/nvim/site/[...]`) and then tries to go into line 43 (`require[[init]]`) and not finding the fennel init file. I can't advance past this, I am not sure if this is something regarding files naming or if it has to do with the flake.

Maybe it's because I changed the name of my repo from nyoom to aum? But it would be weird.

**Comment by a-berg** [comment]
Update: it works normally if I don't use `nix develop` an instead stick to normal installation.

**Comment by shaunsingh** [comment]
Could you do me a favor and try it with `fennel_compiler` set to `tangerine` in `init.lua`, then run `nix develop` followed by `:FnlCompile!`

I've only tested running `nix develop` from `~/.config/nvim`, which is probably why it works with hotpot for me. I imagine your issue is related to this one: https://github.com/rktjmp/hotpot.nvim/issues/54

Switching to tangerine and manually compiling the files should put them under `lua/`, which should in turn work fine with nix

**Comment by rktjmp** [comment]
Saw this linked from the other issue. I got some feedback from a nix user and made some changes, probably fixed. I can only estimate a nix setup with write protected folders in my test suite but that's probably near enough.

**Comment by a-berg** [comment]
> 

So I did the tangerine thing, it fails to find `impatient` (similar error as before but with impatient) so I guess the problem is the same: nvim is still trying to read from `.config`. I may be missing something, sorry to not provide more info 😞

**Comment by shofel** [comment]
@a-berg But the error is about hotpot. Did you get the error about hotpot after switching to tangerine?

**Comment by shofel** [comment]
@a-berg 
maybe you should try with hotpot from its `nix-compat` branch as it's suggested [in the comment](https://github.com/rktjmp/hotpot.nvim/issues/54#issuecomment-1100501344)

I mean, hack init.lua:
- copy-paste the `bootstrap` function, rename it to bootstrap_hotpot
- use this function to bootstrap hotpot // like bootstpap_hotpot('.../hotpot') instead of bootstrap('.../hotpot')
- edit it so that git clones the `nix-compat` branch and switches to it (look at `git` docs)

Of course, this is not a solution, but an experiment to check if the problem exists in `nix-compat` branch of hotpot

**Comment by shofel** [comment]
Or you could also (a lot easier) try to add the line
``` lua
__hotpot_bootstrap_target_dir = vim.fn.stdpath("cache") .. "/some/path"
```
to init.lua before hotpot bootstrapped

**Comment by a-berg** [comment]
I have given it a bit of thought. The hing is, when you clone this repo and *don't link, copy neither clone it into `.config/nvim`", then both tangerine and hotpot fail to find `init.fnl`.

Since the flake file in this repo redefines nvim through an alias to `alias nvim="nvim -u $(pwd)/init.lua"`, i.e. forces nvim to load the config file in the folder once you activate the nix shell through `nix develop` (presumably to load the repo's configuration and test or work on it), _I thought_ this would make the config work whitout having to have it into my `~/.config/nvim` directory.

Let me know if I'm making sense. Basically, there are 2 directories we are taking about: the `.config/nvim` in your `$HOME`, which is where you normally would install any nvim config and I suspect hotpot/tangerine go look into for a config (quite understandably), and a folder where I clone the repo into (like it was any other repo), in which, when using `nix develop` then `nvim`, it fails to load `init.fnl` unless you already have it copied to the standard config dir (i.e. `$HOME/.config/nvim`).

I will close it for now unless someone tells me "no, the behaviour should be that `nix shell` then `nvim` should work when launched from within the folder containing the cloned repo even if you don't have the config in the default path", as it might be a non-issue and just a misunderstanding on my part.

**Comment by rktjmp** [comment]
I wonder if this would make it work:

```bash
alias nvim="nvim -u $(pwd)/init.lua" --cmd "set rtp+=$(pwd)"
```

Which appends the clone dir (nix shell dir?) onto the RTP, then the files should be findable.

> I suspect hotpot/tangerine go look into for a config (quite understandably)

 Unsure about the internals of Tangerine but Hotpot doesn't look for anything particular, just adds an extra loader into the lua environment to match `*.fnl` files. So the error you're getting is just Neovim itself really. If you tried `require("md5")` it would (should?) fail too since `~/aberg/gh/path/lua/md5.lua` is not under the RTP, so Neovim/lua can it find it (assuming nothing else is shipping a `md5` library in your setup).

You should be able to test it pretty easily since we have that md5 library there. Just boot nvim, try to `:lua require("md5")` and expect it to fail, try with the altered rtp and see if the require works.
