### ISSUE TITLE
Add support for Vlime 

### ISSUE THREAD

**Issue by artix-boi** [shaunsingh/nyoom.nvim#61]

**Comment by luxus** [comment]
comon lisp got merged some hours ago

**Comment by shaunsingh** [comment]
Most of the init files are empty, as they're just "shim" files to enable functionality in other programs 

In this case, enabling the common-lisp module will enable 
1. tree-sitter highlighting support for common lisp 
2. Conjure support for common lisp: https://github.com/Olical/conjure/wiki/Quick-start:-Common-Lisp-(Swank)

Cl-lsp isn't support by nvim-lspconfig, though I may send in a PR for lspconfig/mason. Additional improvements will come once https://github.com/Olical/conjure/pull/348 is merged, eventually using slynk instead of slime.

**Comment by artix-boi** [comment]
OOOH, THANK YOU!

**Comment by shaunsingh** [comment]
(I am open to adding additional plugins if they enhance the cl experience though, feel free to send in any recommendations! I'm thinking of adding vim-sexp)

**Comment by artix-boi** [comment]
Can we, instead of using conjure, use vlime as most common lisp users that use neovim use vlime and to some it feels natural and having an option feels good
commands like "\ss"
dont work in when you install vlime

**Comment by shaunsingh** [comment]
vlime support has been added for common lisp, give it a try!

**Comment by artix-boi** [comment]
vlime commands dont work
like '\cc'
