### ISSUE TITLE
Oxocarbon link in README

### ISSUE THREAD

**Issue by Diablo-D3** [shaunsingh/nyoom.nvim#63]
README links to the Nvim Rust bindings repo instead of your own repo at [`https://github.com/shaunsingh/oxocarbon.nvim`](https://github.com/shaunsingh/oxocarbon.nvim), which I expect is what people actually want to see.

Also, although you did Oxocarbon, and we're both Rust fans, I actually suggest switching to [Nightfox](https://github.com/EdenEast/nightfox.nvim/) as it already does a Carbon mimic, but mimics a lot of other themes while having the widest plugin support I've seen out of a flexible Vim theme.

**Comment by shaunsingh** [comment]
I'm not a big fan of the carbon mimic in nightfox. A big part of what makes carbon, carbon is 
1. stick to brighter colors for definitions and duller colors for general syntax
2. introduce a healthy amount of grey and white
3. use bolding to accentuate and distinguish pieces of code 

That being said, the theme rewrite isn't done *yet*, I'll be adding the base16 and colorscheme generator support soon, now that all the basics are in place. Of course, you're welcome to use your own colorscheme or a colorscheme of your choice instead of the builtin one, by simply replacing `colorscheme carbon` with a colorscheme of your choice in `config.fnl`

I'll fix the link in the readme

**Comment by thezaff** [comment]
Please do not change the current theme colors, except few tweaks. I love the colors.

**Comment by gegoune** [comment]
Side question - is nyoom using exactly this https://github.com/shaunsingh/oxocarbon.nvim?

**Comment by Diablo-D3** [comment]
AFAIK, the answer is currently yes.

**Comment by shaunsingh** [comment]
@gegoune Currently, nyoom is running a fennel version of it (https://github.com/shaunsingh/nyoom.nvim/blob/main/fnl/modules/ui/nyoom/config.fnl), which is pretty much the exact same as the `fennel` branch of oxocarbon (https://github.com/shaunsingh/oxocarbon.nvim/tree/fennel)
